input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  mutate {
    add_field => { "pipeline" => "stroynadzor" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "stroynadzor-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => json_lines }
}
